version: "3.8"

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root
    privileged: true
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    ports:
      - 8080:8080
      - 50000:50000
    cap_add:
      - SYS_ADMIN
      - SETFCAP
    security_opt:
      - seccomp:unconfined
    command: /bin/bash -c "apt-get update && apt-get install -y buildah && /usr/local/bin/jenkins.sh"

volumes:
  jenkins_home:
